Add Form Validation to Contact Form #4
ncgau/website pull request #8
Opened 2023-02-03 07:18 UTC by shaanardev

Resolve #4 by:
-  Adds validation to the form by checking that there is a value for the Name and Email input on submit.
-  Adds the following error handling and supporting UX:
     -  Generates error message on form validation for which **required** form inputs were invalid or empty.
     -  Displays error message with red background when form is invalid.
     -  Error message disappears when user is typing controlled by `createEventDispatcher` in `TextInput` component.

2023-02-05 05:09 UTC, KleeUT requested changes
Thanks for your contribution.  I've left a few comments in the code.

2023-02-05 05:09 UTC, KleeUT commented on src/components/contactForm/ContactForm.svelte
> +		<p class={!isFormValid ? 'error' : 'error__hide'}>{errorMessage}</p>
I'd prefer if we were to show the error per field, close to the field.  Maybe something more like this?
![Error messages](https://user-images.githubusercontent.com/1701274/216802855-6c2b9421-2092-408b-8a7e-a708b934fd1f.gif)

2023-02-05 05:09 UTC, KleeUT commented on src/components/contactForm/ContactForm.svelte
> +		background-color: crimson;
This has a bit of a low contrast ratio.  https://contrast-ratio.com/#black-on-crimson
Using a light background and dark text colour shows up better https://contrast-ratio.com/#%236b0000-on-%23ffefef

2023-02-06 11:49 UTC, shaanardev commented
Feedback addressed in latest commit, thank you.

2023-02-11 00:16 UTC, KleeUT approved these changes

2023-02-11 00:16 UTC, merged